services:
  audiobook-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: tts:latest
    platform: linux/amd64
    container_name: audiobook
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - tts-temp:/tmp/audiobook

volumes:
  tts-temp:
    driver: local
